# Generated by Django 2.1.4 on 2018-12-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tmc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
