# Generated by Django 2.1.4 on 2018-12-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApi', '0002_auto_20181216_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uf',
            name='uf',
            field=models.CharField(max_length=255),
        ),
    ]
