# Generated by Django 2.1.4 on 2018-12-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApi', '0003_auto_20181216_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmc',
            name='tipo_tmc',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='dolar',
            name='dolar',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tmc',
            name='tmc',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='uf',
            name='uf',
            field=models.CharField(max_length=25),
        ),
    ]
